FROM node:21.7.1-alpine

RUN mkdir -p /app
WORKDIR /app

COPY ./frontend/package.json ./frontend/package-lock.json ./
COPY ./frontend ./
COPY ./configs/docker-backend.config.json ./src/backend.config.json

ENV PORT 3000
EXPOSE 3000

RUN npm install -g serve
RUN npm install
RUN npm run build

CMD ["serve", "-s", "-l", "3000", "./build"]
