FROM golang:1.22.2-alpine

RUN apk add --no-cache bash curl git jq

# Copy over the configs
WORKDIR /configs
COPY ./configs/ .
COPY ./configs/docker-database.config.json ./database.config.json
COPY ./configs/docker-backend.config.json ./backend.config.json

# Copy over the app
WORKDIR /app
COPY ./backend/go.mod ./backend/go.sum ./
RUN go mod download
COPY ./backend .

# Build the app & run it
RUN go build -o web-sockets ./cmd/web-sockets/web-sockets.go

EXPOSE 8082

CMD ["./web-sockets"]
