apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nft-volume-claim
  labels:
    app: nfts
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
