apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels.backend.name }}
spec:
  replicas: {{ .Values.labels.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.backend.name }}
    spec:
      containers:
        - name: {{ .Values.labels.backend.name }}
          image: {{ .Values.deployments.backend.image }}:{{ .Chart.AppVersion }}-{{ .Values.deployments.sha }}
          command: ["./main"]
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.ports.backend }}
          envFrom:
            - configMapRef:
                name: {{ .Values.labels.backend.name }}-secret
          volumeMounts:
            - mountPath: /app/factions
              name: {{ .Values.volumes.factions.name }}
            - mountPath: /app/templates
              name: {{ .Values.volumes.templates.name }}
            - mountPath: /app/stencils
              name: {{ .Values.volumes.stencils.name }}
      volumes:
        - name: {{ .Values.volumes.factions.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.factions.claim }}
        - name: {{ .Values.volumes.templates.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.templates.claim }}
        - name: {{ .Values.volumes.stencils.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.stencils.claim }}
