apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.labels.backend.name }}-secret
  labels:
    app: {{ .Values.labels.backend.name }}
data:
  ART_PEACE_CONTRACT_ADDRESS: {{ .Values.contracts.artPeace }}
  USERNAME_STORE_CONTRACT_ADDRESS: {{ .Values.contracts.usernameStore }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
