apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.labels.postgres.name }}-volume-claim
  labels:
    app: {{ .Values.labels.postgres.name }}
spec:
  storageClassName: {{ .Values.volumes.postgres.class }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.postgres.storage }}
