apiVersion: v1
kind: Service
metadata:
  name: admin-backend
  labels:
    app: admin-backend
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8080
  selector:
    app: admin-backend
