apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.labels.redis.name }}-volume-claim
  labels:
    app: {{ .Values.labels.redis.name }}
spec:
  storageClassName: {{ .Values.volumes.redis.class }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.redis.storage }}
