apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.labels.indexer.name }}-secret
  labels:
    app: {{ .Values.labels.indexer.name }}
data:
  ART_PEACE_CONTRACT_ADDRESS: {{ .Values.contracts.artPeace }}
  USERNAME_STORE_ADDRESS: {{ .Values.contracts.usernameStore }}
  NFT_CONTRACT_ADDRESS: {{ .Values.contracts.nft }}
  CONSUMER_TARGET_URL: http://{{ .Values.labels.consumer.name }}.art-peace-sepolia.svc.cluster.local:{{ .Values.ports.consumer }}/consume-indexer-msg
  APIBARA_STREAM_URL: {{ .Values.apibara.streamUrl }}
  AUTH_TOKEN: {{ .Values.apibara.authToken }}
  PERSIST_TO_REDIS: redis://{{ .Values.labels.redis.name }}.art-peace-sepolia.svc.cluster.local:{{ .Values.ports.redis }}
  INDEXER_ID: {{ .Values.apibara.indexerId }}
