apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: 'redis:7.2.4-alpine'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          envFrom:
            - configMapRef:
                name: redis-secret
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-volume-claim
