apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume-claim
  labels:
    app: redis
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
