name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: scarb fmt --check
        working-directory: onchain
      - run: scarb build
        working-directory: onchain
      - name: go formatting ( gofmt -s -w . )
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
        working-directory: backend
